export const SUBMIT_FORM = 'SUBMIT_FORM';
export const TEST = 'TEST';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const REQUEST_API = 'REQUEST_API';
export const REQUEST_API_COMPLETE = 'REQUEST_API_COMPLETE';
export const REQUEST_API_FAIL = 'REQUEST_API_FAIL';
export const REQUEST_API_COINS = 'REQUEST_API_COINS';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
